### ISSUE TITLE
Cursor Pointer on Navbar

### ISSUE THREAD

**Issue by Ayushhgupta39** [Nitishpal68/Portfolio-#3]
There is no Cursor Pointer in Navbar.

After fixing it, it will look more natural while using.
Please assign me this.

**Comment by Nitishpal68** [comment]
Assigned

**Comment by Nitishpal68** [comment]
Assigned @Ayushhgupta39

**Comment by Ayushhgupta39** [comment]
Please do assign Properly and add Hacktoberfest and hacktoberfest-accepted label! Only then I will be able to raise my PR.

**Comment by Nitishpal68** [comment]
Done

**Comment by Ayushhgupta39** [comment]
It is showing Not participating in the Hacktoberfest website. Please fix this and add the following labels.
<img width="236" alt="image" src="https://user-images.githubusercontent.com/96309609/195769369-f221f7de-2468-4983-9ec8-8ea1be3e7cdf.png">
